######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 6 13:09:40 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Window.hpp \
    PrivateTab.hpp
SOURCES += main.cpp Window.cpp \
    PrivateTab.cpp
