######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 19 11:54:14 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CFLAGS += -fpermissive
CXXFLAGS += -fpermissive

# Input
HEADERS += ConnexionDialog.hpp PrivateTab.hpp Window.hpp ../Server/common.h
SOURCES += ConnexionDialog.cpp main.cpp PrivateTab.cpp Window.cpp
